<?php
return [
    [
        'key' => 'ethnic',
        'value' => 'Kinh',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '1',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Tày',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '2',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Thái',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '3',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Hoa',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '4',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Khơ-me',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '5',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Mường',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '6',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Nùng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '7',
    ],
    [
        'key' => 'ethnic',
        'value' => 'HMmông',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '8',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Dao',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '9',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Gia-rai',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '10',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Ngái',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '11',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Ê-đê',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '12',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Ba na',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '13',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Xơ-Đăng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '14',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Sán Chay',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '15',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Cơ-ho',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '16',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Chăm',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '17',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Sán Dìu',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '18',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Hrê',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '19',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Mnông',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '20',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Ra-glai',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '21',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Xtiêng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '22',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Bru-Vân Kiều',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '23',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Thổ',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '24',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Giáy',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '25',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Cơ-tu',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '26',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Gié Triêng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '27',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Mạ',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '28',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Khơ-mú',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '29',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Co',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '30',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Tà-ôi',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '31',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Chơ-ro',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '32',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Kháng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '33',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Xinh-mun',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '34',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Hà Nhì',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '35',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Chu ru',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '36',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Lào',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '37',
    ],
    [
        'key' => 'ethnic',
        'value' => 'La Chí',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '38',
    ],
    [
        'key' => 'ethnic',
        'value' => 'La Ha',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '39',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Phù Lá',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '40',
    ],
    [
        'key' => 'ethnic',
        'value' => 'La Hủ',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '41',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Lự',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '42',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Lô Lô',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '43',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Chứt',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '44',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Mảng',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '45',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Pà Thẻn',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '46',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Co Lao',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '47',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Cống',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '48',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Bố Y',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '49',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Si La',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '50',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Pu Péo',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '51',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Brâu',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '52',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Ơ Đu',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '53',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Rơ măm',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '54',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Người nước ngoài',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '55',
    ],
    [
        'key' => 'ethnic',
        'value' => 'Không rõ',
        'type' => App\Enums\EMasterData::TYPE_ETHNIC,
        'order' => '56',
    ],

];
